Front-end:
	bash components/Front-end.sh
cart:
	bash components/cart.sh
mongodb:
	bash components/mongodb.sh
catalogue:
	bash components/catalogue.sh
redis:
	bash components/redis.sh
user:
	bash components/User.sh
mysql:
	bash components/Mysql.sh
shipping:
	bash components/Shipping.sh
RabbitMQ:
	bash components/RabbitMQ.sh